apiVersion: v1
kind: Pod
metadata:
  name: queueapp
  labels:
    app: queueapp
spec:
  containers:
  - name: queueapp
    image: richardchesterwood/k8s-fleetman-queue:release1




---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queueapp
spec:
  selector:
    app: queueapp
  ports:
  - name: http
    port: 8161
    targetPort: 8161
    nodePort: 30081
  type: NodePort

