apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp
  labels:
    app: webapp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: myapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0



---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp 

spec:
  selector:
    app: webapp
  ports:
  - name: http
    port: 80
    targetPort: 80

    nodePort: 30080
  type: NodePort
