version: "3"

env:
  BORDER: double
  BORDER_FOREGROUND: "212"
  PADDING: "1 1"
  MARGIN: "1 1"
  NAMESPACE: basic


tasks:
  00-find-node-ip:
    desc: "find kind node ip"
    cmds:
      - export NODE_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' kind-control-plane)
  01-create-namespace:
    desc: "Create a namespace for these examples and set as default"
    cmds:
      - kubectl apply -f Namespace.yaml
      - kubens ${NAMESPACE}

  02-apply-manual-pv-pvc-pod-kind:
    desc: "Apply the configuration for a manually provisioned local PVC and a pod to consume it"
    cmds:
      - kubectl apply -f first-pod.yaml
      # - kubectl apply -f kind/PersistentVolumeClaim.manual-pv-kind.yaml
      # - kubectl apply -f kind/Pod.manual-pv-and-pvc-kind.yaml
      - kubectl describe pod webapp
      - kubectl exec webapp ls
      - kubectl -it exec webapp sh 